name: FRED Data Cache Builder

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours

permissions:
  contents: write

jobs:
  fetch-fred:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip requests pandas

      - name: Fetch FRED data and build cache
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          mkdir -p data
          python - <<'PY'
          import os, json, pandas as pd, requests
          from datetime import datetime

          API_KEY = os.getenv("FRED_API_KEY")
          BASE = "https://api.stlouisfed.org/fred/series/observations"

          def fetch(sid):
              r = requests.get(BASE, params={
                  "series_id": sid,
                  "api_key": API_KEY,
                  "file_type": "json",
                  "observation_start": "2018-01-01"
              })
              r.raise_for_status()
              obs = r.json()["observations"]
              df = pd.DataFrame(obs)
              df["value"] = pd.to_numeric(df["value"], errors="coerce")
              df = df.dropna(subset=["value"])
              return df

          # Main series
          series_ids = {
              "T10Y3M": ("DGS10", "DGS3MO"),  # 10y–3m
              "CREDIT": ("BAA", "AAA"),       # BAA–AAA
              "UNRATE": ("UNRATE",),          # Unemployment
              "SP500": ("SP500",),            # S&P 500
              "NFCI": ("NFCI",),              # Financial conditions
          }

          data = {}
          for key, ids in series_ids.items():
              if len(ids) == 2:
                  a, b = fetch(ids[0]), fetch(ids[1])
                  merged = pd.merge(a, b, on="date", suffixes=("_a","_b"))
                  merged["value"] = merged["value_a"] - merged["value_b"]
                  data[key] = float(merged["value"].iloc[-1])
              else:
                  df = fetch(ids[0])
                  data[key] = float(df["value"].iloc[-1])

          payload = {
              "fetched_at_utc": datetime.utcnow().isoformat() + "Z",
              "series": data
          }

          with open("data/fred_cache.json", "w") as f:
              json.dump(payload, f, indent=2)
          PY

      - name: Commit cache file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/fred_cache.json
          git commit -m "Update FRED cache" || echo "No changes"
          git push
